### ISSUE TITLE
ray dependency forbids upgrading Python to 3.12 or above

### ISSUE THREAD

**Issue by chhotii-alex** [ArnaoutLab/diversity#88]
See here: https://github.com/ray-project/ray/issues/40211

Last I saw, there were no updates as to timeframe for making ray compatible with Python 3.12 and above, nor a description of what the issues might be (other than "get around to it"). If/when there's an update there, this becomes easily fixable...

If ray's support for 3.12 drags on forever (and I note that they are now _two_ major versions of Python behind; ideally one would support 3.13 as well) then do we consider:

* making the ray dependency an "extra"?
* porting the code to some other parallelization framework?
* volunteering to contribute whatever the ray team needs to get past the bottleneck?
* Some combination of the above? (Other parallelization in the base module, plus ray in an extra?)

I don't know what to do about this. ray is nice for its clean API plus the ability to parallelize across a Kubernetes cluster. If we want to support truly huge datasets, I would be really loathe to abandon the ability to parallelize across a Kubernetes cluster.

**Comment by Elliot-D-Hill** [comment]
I've wondered about making Pytorch an optional dependency (in addition to or as a replacement for Ray) for a while now. It would likely confer orders of magnitude speed up with GPU acceleration because Zp_i can be computed in parallel. Since our API is already Numpy compliant, it would hardly take any additional code. 

The only downside is that all similarity calculations would have to be vectorized. So, we could not calculate the Levenshtein distance, for example. That said, learned embeddings/metrics have been more performant than bespoke metrics for the better part of the last decade on just about every application people compare them on. 

So, if you wanted to calculate antibody sequence similarities, you would first convert the sequences to vectors with, e.g., word2vec, and then compute your similarities with the learned vectors. And if you're still dying to use Levenshtein distance then you could learn a vectorized version of it.

**Comment by chhotii-alex** [comment]
I don't agree with the idea of breaking existing functionality (for example, bespoke similarity functions). However we could have our cake and eat it too by putting both use of ray and use of pytorch into separate "extras" (API would have to become a bit more complex to allow the user to specify, but that's a worthwhile trade-off).

**Comment by chhotii-alex** [comment]
Plan is to make the part of greylock that depends on ray an optional dependency
- This forces us to change the API (at least a little bit); ok if we bump major version
- pass name of backend as an optional parameter

**Comment by chhotii-alex** [comment]
Note that Ray now supports Python 3.12. Not sure if it supports 3.13 yet...

Moving use of Ray into an extra is still worthwhile. Ray is burdened by so many dependencies, which themselves may not all keep up with Python upgrades, so this drama may re-occur. Making this a possible cut point in the dependency chain would be good.

**Comment by chhotii-alex** [comment]
We've handled this as best we can by making this an optional dependency.
